name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'notify vercel'
      uses: 'vercel/repository-dispatch/actions/status@v1'
      with:
        name: 'Vercel - vc-flight-booking-123: lint'
